### GENERAL LOADS
eval "$(fnm env --use-on-cd --shell zsh)"
eval "$(dms completion zsh)"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### OHMYZSH

## EXPORTS
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export PYTHONPATH="$HOME/dev"
export GOPATH="$HOME/.go"
export SDL_VIDEODRIVER=wayland
export SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock

## STYLES
zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' frequency 13
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

## OPTIONS
# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HISTSIZE=500000
SAVEHIST=500000
HIST_STAMPS="dd/mm/yyyy"

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY

## PLUGINS (managed by NixOS oh-my-zsh module in users/joel/shell.nix)

## LOAD
#source $ZSH/oh-my-zsh.sh
#if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
#    builtin source ${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration
#fi
### OTHERS

## ENV
export LANG=es_ES.UTF-8
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='nvim'
else
   export EDITOR='zeditor'
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities joel joel_ssb

## BINDKEYS
toggle_sudo() {
  if [[ $BUFFER =~ ^\s*sudo\  ]]; then
    BUFFER=${BUFFER#sudo }  # Remove sudo
  else
    BUFFER="sudo $BUFFER"  # Prepend sudo
  fi
  CURSOR=$#BUFFER  # Move cursor to end
}
zle -N toggle_sudo
bindkey '^S' toggle_sudo
bindkey "^H" backward-kill-word

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
